const ProductList = [
  {
    id: 0,
    asin: "B0DFY3XCB6",
    product_title: "Samsung Galaxy M05 (Mint Green, 4GB RAM, 64 GB Storage) | 50MP Dual Camera | Bigger 6.7\" HD+ Display | 5000mAh Battery | 25W Fast Charging | 2 Gen OS Upgrade & 4 Year Security Update | Without Charger",
    product_price: "₹7,999",
    product_original_price: "₹9,999",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 588,
    product_url: "https://www.amazon.in/dp/B0DFY3XCB6",
    product_photo: "https://m.media-amazon.com/images/I/81T3olLXpUL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹7,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 1,
    asin: "B0CNX6WVZF",
    product_title: "Redmi 13C 5G (Starlight Black, 6GB RAM, 128GB Storage) | MediaTek Dimensity 6100+ 5G | 90Hz Display",
    product_price: "₹10,999",
    product_original_price: "₹15,999",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 9693,
    product_url: "https://www.amazon.in/dp/B0CNX6WVZF",
    product_photo: "https://m.media-amazon.com/images/I/81nMsYgIHdL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹10,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 2,
    asin: "B0CQYN9QDQ",
    product_title: "OnePlus 12R (Cool Blue, 16GB RAM, 256GB Storage)",
    product_price: "₹40,999",
    product_original_price: "₹45,999",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 3996,
    product_url: "https://www.amazon.in/dp/B0CQYN9QDQ",
    product_photo: "https://m.media-amazon.com/images/I/717JX3femML._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹40,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 3,
    asin: "B0CW5F732B",
    product_title: "realme NARZO 70 Pro 5G (Glass Gold, 8GB RAM,256GB Storage) Dimensity 7050 5G Chipset | Horizon Glass Design | Segment 1st Flagship Sony IMX890 OIS Camera",
    product_price: "₹16,998",
    product_original_price: "₹26,999",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 5446,
    product_url: "https://www.amazon.in/dp/B0CW5F732B",
    product_photo: "https://m.media-amazon.com/images/I/71Qwha+BcbL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹16,998",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "4K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 4,
    asin: "B0D5YCYS1G",
    product_title: "OnePlus Nord CE4 Lite 5G (Super Silver, 8GB RAM, 128GB Storage)",
    product_price: "₹19,999",
    product_original_price: "₹20,999",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 2902,
    product_url: "https://www.amazon.in/dp/B0D5YCYS1G",
    product_photo: "https://m.media-amazon.com/images/I/61Io5-ojWUL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹19,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    coupon_text: "Save ₹2,000 with coupon",
    has_variations: true,
  },
  {
    id: 5,
    asin: "B0C9QS5G2R",
    product_title: "OnePlus Nord CE 3 5G (Aqua Surge, 8GB RAM, 128GB Storage)",
    product_price: "₹16,999",
    product_original_price: "₹26,999",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 15410,
    product_url: "https://www.amazon.in/dp/B0C9QS5G2R",
    product_photo: "https://m.media-amazon.com/images/I/6175SlKKECL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹16,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 6,
    asin: "B0CNX89QR8",
    product_title: "Redmi 13C 5G (Starlight Black, 4GB RAM, 128GB Storage) | MediaTek Dimensity 6100+ 5G | 90Hz Display",
    product_price: "₹9,199",
    product_original_price: "₹13,999",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 9693,
    product_url: "https://www.amazon.in/dp/B0CNX89QR8",
    product_photo: "https://m.media-amazon.com/images/I/81nMsYgIHdL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹9,199",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 7,
    asin: "B0CDXHYHZ6",
    product_title: "Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Triple AI Camera | 11GB RAM (6GB RAM + 5GB Virtual RAM) | 128GB Storage | 5000mAh Battery | 2 Years Android Upgrades | 20W Charger Included | So Grey",
    product_price: "₹11,499",
    product_original_price: "₹16,499",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 5387,
    product_url: "https://www.amazon.in/dp/B0CDXHYHZ6",
    product_photo: "https://m.media-amazon.com/images/I/71oIjjNm+nL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 8,
    asin: "B0CDXHYHZ6",
    product_title: "Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Triple AI Camera | 11GB RAM (6GB RAM + 5GB Virtual RAM) | 128GB Storage | 5000mAh Battery | 2 Years Android Upgrades | 20W Charger Included | So Grey",
    product_price: "₹11,499",
    product_original_price: "₹16,499",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 5387,
    product_url: "https://www.amazon.in/dp/B0CDXHYHZ6",
    product_photo: "https://m.media-amazon.com/images/I/71oIjjNm+nL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 9,
    asin: "B0D3GY8SC1",
    product_title: "realme NARZO N65 5G (Deep Green 4GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim 190g Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
    product_price: "₹11,498",
    product_original_price: "₹13,999",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 1429,
    product_url: "https://www.amazon.in/dp/B0D3GY8SC1",
    product_photo: "https://m.media-amazon.com/images/I/717sEAdy02L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,498",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    coupon_text: "Save ₹500 with coupon",
    has_variations: true,
  },
  {
    id: 10,
    asin: "B0D9NFLZMQ",
    product_title: "realme NARZO N65 5G (Amber Gold 8GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
    product_price: "₹13,498",
    product_original_price: "₹15,999",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 1429,
    product_url: "https://www.amazon.in/dp/B0D9NFLZMQ",
    product_photo: "https://m.media-amazon.com/images/I/71ocQY+G2XL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹13,498",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    coupon_text: "Save ₹1,000 with coupon",
    has_variations: true,
  },
  {
    id: 11,
    asin: "B0DDY9HMJG",
    product_title: "Motorola G45 5G (Brilliant Blue, 8GB RAM, 128GB Storage)",
    product_price: "₹13,430",
    product_original_price: "₹14,999",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 26,
    product_url: "https://www.amazon.in/dp/B0DDY9HMJG",
    product_photo: "https://m.media-amazon.com/images/I/81dl4dQY3BL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹13,430",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Thu, 14 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 12,
    asin: "B07WHQZ93Z",
    product_title: "vivo Y18i (Space Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers |Without Charger",
    product_price: "₹7,999",
    product_original_price: "₹11,999",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 39,
    product_url: "https://www.amazon.in/dp/B07WHQZ93Z",
    product_photo: "https://m.media-amazon.com/images/I/61slrN5n-FL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹7,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 13,
    asin: "B0DC1GNY41",
    product_title: "POCO M6 5G, Orion Blue (4GB, 64GB)",
    product_price: "₹8,299",
    product_original_price: "₹9,499",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 17,
    product_url: "https://www.amazon.in/dp/B0DC1GNY41",
    product_photo: "https://m.media-amazon.com/images/I/719LcA76E5L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹8,299",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: false,
  },
  {
    id: 14,
    asin: "B07WHSQDH8",
    product_title: "iQOO 12 5G (Alpha, 12Gb Ram, 256Gb Storage) |India&#x27;s 1St Snapdragon 8 Gen 3 Backcase for Mobile Platform | India&#x27;s Only Flagship with 50Mp + 50Mp + 64Mp Camera, Black",
    product_price: "₹52,999",
    product_original_price: "₹59,999",
    currency: "INR",
    product_star_rating: "4.5",
    product_num_ratings: 2766,
    product_url: "https://www.amazon.in/dp/B07WHSQDH8",
    product_photo: "https://m.media-amazon.com/images/I/61TsYMoy2RL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹52,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  },
  {
    id: 15,
    asin: "B08VB57558",
    product_title: "Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM, 128GB Storage)",
    product_price: "₹30,490",
    product_original_price: "₹74,999",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 36515,
    product_url: "https://www.amazon.in/dp/B08VB57558",
    product_photo: "https://m.media-amazon.com/images/I/81vDZyJQ-4L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹30,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery Thu, 7 Nov Or fastest delivery Tomorrow, 6 Nov",
    has_variations: true,
  }
];

export default ProductList;
