const FashionProduct = [
    {
        id: 0,
        asin: "B0DM5FYXKJ",
        product_title: "DANNY FASHION Sport Bra Thin Strap Sport Bra Padded for Women Comfort Zone Regular",
        product_price: "₹299",
        product_original_price: "₹499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM5FYXKJ",
        product_photo: "https://m.media-amazon.com/images/I/31TBhfW8j3L._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹299",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 1,
        asin: "B0DM5FY2XF",
        product_title: "METROMANTAR You Run : Tranform Your Fashion with Christmas Hoodie/Hoodie for Mens &amp; Boys",
        product_price: "₹749",
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM5FY2XF",
        product_photo: "https://m.media-amazon.com/images/I/51gRv7X9t-L._SY741_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹749",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 2,
        asin: "B0DM5GB8BJ",
        product_title: "DANNY FASHION Sport Bra Padded for Women Sport Bra Thin Strap Cotton Comfot Zone",
        product_price: "₹299",
        product_original_price: "₹499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM5GB8BJ",
        product_photo: "https://m.media-amazon.com/images/I/712pxQTDm2L._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹299",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 3,
        asin: "B0DLW29Y3J",
        product_title: "Generic Loris Fashion, Cotton Printed Bandana Headband Scarf Handkerchiefs Wristband, Neckerchief Head For Face Mask bandanas",
        product_price: "₹249",
        product_original_price: "₹799",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DLW29Y3J",
        product_photo: "https://m.media-amazon.com/images/I/61Y76vQwjGL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹249",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 4,
        asin: "B0DM4Y27TD",
        product_title: "DTR FASHION Lycra Stretchable Gym Track Pants for Women &amp; Tights for Women Workout,Running - Pack of 2",
        product_price: "₹499",
        product_original_price: "₹1,999",
        currency: "INR",
        product_star_rating: "3.9",
        product_num_ratings: 4,
        product_url: "https://www.amazon.in/dp/B0DM4Y27TD",
        product_photo: "https://m.media-amazon.com/images/I/71A0NpV1gaL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    }, {
        id: 5,
        asin: "B0DD3QH1R1",
        product_title: "Leriya Fashion Printed Regular Rayon Floral Ethnic Co-ord Kurta Set for Women (Available in 2XL and 3XL)",
        product_price: "₹499",
        product_original_price: "₹1,999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DD3QH1R1",
        product_photo: "https://m.media-amazon.com/images/I/51a4j0YLDjL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: "FREE Delivery by Amazon",
        has_variations: false,
    },
    {
        id: 6,
        asin: "B0DM2P24KW",
        product_title: "YOUWE FASHION ; Let&#x27;s Customize! Kids Unisex Fleece Thermal Set, 3 Pieces, Blue, Grey, Brown",
        product_price: "₹699",
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2P24KW",
        product_photo: "https://m.media-amazon.com/images/I/51X19UyyiBL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹699",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 7,
        asin: "B0DM2NVZBR",
        product_title: "Hozify Double Sided Tape for Clothes &amp; Body – Invisible Double-Sided Fashion Tape for Women | Transparent,Fabric-Friendly Bra Stickers | Perfect for Clothing,Bikini,and Body | 36 Count Strips",
        product_price: "₹119",
        product_original_price: null,
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2NVZBR",
        product_photo: "https://m.media-amazon.com/images/I/817mkibFXIL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹119",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "No featured offers available",
        delivery: null,
        has_variations: false,
    },
    {
        id: 8,
        asin: "B0DM2LDQ6C",
        product_title: "Ukal Winter Fashion Men&#x27;s and Women&#x27;s Wool Solid Night Suit Top and Pyjama Set",
        product_price: "₹699",
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2LDQ6C",
        product_photo: "https://m.media-amazon.com/images/I/319Perfo0bL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹699",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: "FREE Delivery by Amazon",
        has_variations: false,
    },
    {
        id: 9,
        asin: "B0DKXRFYLH",
        product_title: "Generic Fashion-Forward Hijab Undercap for Women | Pack of 2 Multicolour",
        product_price: "₹199",
        unit_price: "₹99.50",
        unit_count: 2,
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DKXRFYLH",
        product_photo: "https://m.media-amazon.com/images/I/712D8HqLxeL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹199",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "(₹99.50₹99.50/count)",
        delivery: null,
        has_variations: false,
    },
    {
        id: 10,
        asin: "B0DM2CV5W2",
        product_title: "Leriya Fashion co-ord Set for Women Summer| co-ord Set for Women (XXX-Large, Black) co-ord set for women western wear summer| co-ord set for women (XXX-Large, LavenderBlush)",
        product_price: "₹1,092",
        product_original_price: "₹3,998",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2CV5W2",
        product_photo: "https://m.media-amazon.com/images/I/516fCB0V4vL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹1,092",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "List: ",
        delivery: "FREE Delivery by Amazon",
        has_variations: false,
    },
    {
        id: 11,
        asin: "B0DM2BXSQW",
        product_title: "MOOVIO FASHION Women&#x27;s Trendy Crop Top - Stylish &amp; Modern Design, Comfortable Fit, Round Neck Crop Top for Women and Girls, Ideal for Casual Outings, Parties and Everyday Wear",
        product_price: "₹499",
        product_original_price: "₹699",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2BXSQW",
        product_photo: "https://m.media-amazon.com/images/I/41JE45zCQlL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 12,
        asin: "B0DM29SWPZ",
        product_title: "MOOVIO FASHION Women&#x27;s Trendy Crop Top - Stylish &amp; Modern Design, Comfortable Fit, Round Neck Crop Top for Women and Girls, Ideal for Casual Outings, Parties and Everyday Wear",
        product_price: "₹499",
        product_original_price: "₹699",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM29SWPZ",
        product_photo: "https://m.media-amazon.com/images/I/41JE45zCQlL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 13,
        asin: "B0DM2B1HN7",
        product_title: "Women Planet Cotton Printed Kurta And Pant Set For Women And Girls, Trending Latest Fashion",
        product_price: "₹699",
        product_original_price: "₹2,599",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM2B1HN7",
        product_photo: "https://m.media-amazon.com/images/I/51Gzzsl2oXL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹699",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 14,
        asin: "B0DM26GSD8",
        product_title: "Generic Women&#x27;s Pure Cotton Nightwear Casual Nighty (Red FASHION-163 XXL)",
        product_price: "₹549",
        product_original_price: "₹1,499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM26GSD8",
        product_photo: "https://m.media-amazon.com/images/I/612PWuZFHjL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹549",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 15,
        asin: "B0DM26576B",
        product_title: "Generic Women&#x27;s Pure Cotton Nightwear Casual Nighty (Yellow FASHION-99 Free)",
        product_price: "₹549",
        product_original_price: "₹1,499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM26576B",
        product_photo: "https://m.media-amazon.com/images/I/41PCuGkqcdL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹549",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 16,
        asin: "B0DM267HD5",
        product_title: "Generic Women&#x27;s Pure Cotton Nightwear Casual Nighty (FASHION-1084 XL) Red",
        product_price: "₹549",
        unit_price: "₹274.50",
        unit_count: 2,
        product_original_price: "₹1,499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM267HD5",
        product_photo: "https://m.media-amazon.com/images/I/71nrpFR5cmL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹549",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "(₹274.50₹274.50/count)",
        delivery: null,
        has_variations: false,
    }
]
export default FashionProduct;