const MenFashionProductList = [
    {
        id: 0,
        asin: "B0DM5FY2XF",
        product_title: "METROMANTAR You Run : Tranform Your Fashion with Christmas Hoodie/Hoodie for Mens & Boys",
        product_price: 749,
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DM5FY2XF",
        product_photo: "https://m.media-amazon.com/images/I/61lKF+KRqGL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹749",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 1,
        asin: "B0DLW5PNMN",
        product_title: "Generic Stylish Pure Cotton Black Oversized T-Shirt | Round Neck Drop Shoulder | Unisex Casual Fashion Tshirt for Men",
        product_price: 499,
        product_original_price: "₹799",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DLW5PNMN",
        product_photo: "https://m.media-amazon.com/images/I/6183i57dguL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 2,
        asin: "B0DLH422PH",
        product_title: "generic Stylish Pure Cotton Black Oversized T-Shirt | Round Neck Drop Shoulder | Unisex Casual Fashion Tee for Men",
        product_price: 499,
        product_original_price: "₹799",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DLH422PH",
        product_photo: "https://m.media-amazon.com/images/I/6183i57dguL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 3,
        asin: "B0DLVHDD4X",
        product_title: "LOOKRATIVE FASHIONS Men&#x27;s Black Cotton T-Shirt with LF Logo Print, Regular Fit",
        product_price: 698,
        product_original_price: "₹999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DLVHDD4X",
        product_photo: "https://m.media-amazon.com/images/I/51DIsrczd2L._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹698",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: "FREE Delivery",
        has_variations: false,
    },
    {
        id: 4,
        asin: "B0DLT29CNV",
        product_title: "Generic U R Fashion Men's RED Double Pocket Cotton Shirt, Long Sleeves",
        product_price: 499,
        product_original_price: "₹799",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DLT29CNV",
        product_photo: "https://m.media-amazon.com/images/I/41EyA31DPqL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 5,
        asin: "B0DB744C98",
        product_title: "Blaq Ash Men's Casual Quilted Puffer Coat, Warm Winter Jacket for Trendy Fashion, Zipper",
        product_price: 1399,
        product_original_price: "₹3,999",
        currency: "INR",
        product_star_rating: "1",
        product_num_ratings: 1,
        product_url: "https://www.amazon.in/dp/B0DB744C98",
        product_photo: "https://m.media-amazon.com/images/I/71MKJbdW5EL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹1,399",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: "FREE Delivery by Amazon",
        has_variations: false,
    },
    {
        id: 6,
        asin: "B093ZNFH18",
        product_title: "ikiki-tech Skinny Slim Fashion Necktie for men Novelty Conversational Neckwear Ties (Video Game Controller Gadgets Pattern), As Shown, Large",
        product_price: 3483,
        product_original_price: null,
        currency: "INR",
        product_star_rating: "3.1",
        product_num_ratings: 8,
        product_url: "https://www.amazon.in/dp/B093ZNFH18",
        product_photo: "https://m.media-amazon.com/images/I/71pR1LessIL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹3,483.68",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: null,
        delivery: null,
        has_variations: false,
    },
    {
        id: 7,
        asin: "B0DJYJVDCR",
        product_title: "Urbano Fashion Men's Cotton Full Sleeve Regular Fit Casual Solid Shirt",
        product_price: 699,
        product_original_price: "₹1,699",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DJYJVDCR",
        product_photo: "https://m.media-amazon.com/images/I/618ji0ov9wL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹699",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: "FREE Delivery by Amazon",
        has_variations: true,
    },
    {
        id: 8,
        asin: "B0DL3L6ZT8",
        product_title: "AREAL FASHION Men's Soft parashut Cargo Trousers with Multiple Pockets, Drawstring Waist",
        product_price: 449,
        product_original_price: "₹1,200",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL3L6ZT8",
        product_photo: "https://m.media-amazon.com/images/I/41XcsXJNmPL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹449",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 9,
        asin: "B0DL78DZLV",
        product_title: "oiin Stylish Designer Half Zip Collar Fashion Black Blue Green Wine Navy Sweatshirt with no Pockets for Men Fleece Fabric 2025 S M L XL XXL 056",
        product_price: 649,
        product_original_price: "₹1,899",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL78DZLV",
        product_photo: "https://m.media-amazon.com/images/I/61iCi5rKlrL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹649",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 10,
        asin: "B0DL79C27R",
        product_title: "Generic OOIMA Fashion Regular Fit Round Neck PP Drifit Tshirts",
        product_price: 199,
        product_original_price: "₹499",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL79C27R",
        product_photo: "https://m.media-amazon.com/images/I/61F-ZRbBJdL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹199",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 11,
        asin: "B0DL66VY68",
        product_title: "NUKAICHAU Fashion Leather Belt | Office Wear Belt | Formal Belt Reversible | For Men | Easy Adjustable Size 16-46 | Colour Black/Brown | Gift Box included | KT8_920_Free_BL3.415",
        product_price: 1499,
        product_original_price: "₹1,999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL66VY68",
        product_photo: "https://m.media-amazon.com/images/I/512Bxa6z5gL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹1,499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 12,
        asin: "B0DL6987KF",
        product_title: "NUKAICHAU Textured Leather Belt | Fashion Leather Belt | PU Leather Belt | For Men | Easy Adjustable Size 16-46 | Colour Black/Brown | Gift Box included | KT8_920_P_BL2.380",
        product_price: 699,
        product_original_price: "₹1,999",
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL6987KF",
        product_photo: "https://m.media-amazon.com/images/I/61EZvqWh4DL._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹699",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    },
    {
        id: 13,
        asin: "B0DL65T9DF",
        product_title: "NUKAICHAU Synthetic Belt | Reversible Formal Leather Belt | Fashion Belt | For Men | Easy Adjustable Size 16-46 | Colour Black/Brown | Gift Box included | KT8_920_Free_BL1.307",
        product_price: 1499,
        product_original_price: 1999,
        currency: "INR",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.in/dp/B0DL65T9DF",
        product_photo: "https://m.media-amazon.com/images/I/51hvFB7J-8L._AC_UL960_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹1,499",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery: null,
        has_variations: false,
    }                                        

]

export default MenFashionProductList;
